### ISSUE TITLE
Synchronous client APIs

### ISSUE THREAD

**Issue by tekjar** [tekjar/rumqtt#77]
This [example](https://github.com/tekjar/rumq/blob/sync/rumq-client/examples/syncpubsub.rs) demonstrates how to use sync APIs

Please give me feedback if this improves the ease of use. Will be merged by the end of this week if there are no comments. Feel free to tag other people who might be interested

@TotalKrill @qm3ster @MightyPork @amrx101

**Comment by TotalKrill** [comment]
I cant really put a finger on it, but this feels weird, also how would I handle failing connections here? or know when a reconnect has happened, or stuff like that. 

Those events are interesting, but often unrelated to what I want to do, which is send/receive data. Sometimes i want to know about disconnections and such so that I can fix so my send/receive does work again.

``` rust
let opts = MqttOptions().set_reconnect(...).set_throttle(...);
let client = MqttClient::new("clientname", opts);

// let connection be a real object that you can run connection.run() on or connection.run_in_background() or connection.events().next().

let connection = client.connect().expect("couldnt connect");
let conn_handle = connection.run_background();

let hello_sub = client.subscribe("hello/world").expect("client could not subscribe");

let send_client = client.clone();
thread::spawn(move || {
    for i in 1..10 {
        send_client.publish("hello/world", i.as_bytes()).expect("Could not publish");
    }
)


while let Ok(num) = hello_sub.next() {
    println!("{}",num);
}

client.disconnect();
conn_handle.join();  // wait until the connection has died

```
What do you think about something like this for an API? Its quite similar to rumqtt. But separates the connection part from the client part, making the client able to be send and sync, while hiding the internals from a user if wanted.

**Comment by MightyPork** [comment]
@TotalKrill I don't know about this way to do subscriptions... It looks fine in the example, but in a more complex application you'd need to manage many such "subscription channels" - instead of having a single channel like in rumqtt and matching on the topic string. It quickly gets messy... though I also see its appeal if your subscriptions are known at compile time.

I plan to try porting our application to this experimental client, if I find the time, to see how it feels in real code

**Comment by qm3ster** [comment]
I think the original interface by @tekjar  is adequate.

I do like methods like `.publish` and `.subscribe` like @TotalKrill suggests, but I feel like end users should just wrap the channel themselves. In fact it's `Publish::new()` and such that I don't like, because I always end up making my own client with methods, because I need to for instance set retain to true sometimes, so I have `publish` and `retain` methods.

As for the subscription channels, that's definitely something useful for a high level interface. They can also have a `.close()` method that unsubscribes but gives you the channel back so you can drain the last messages that had time to come in.

Tbh I only use async, because I also use timers and such, but I also made a toy synchronous example that looks very different, so I'll post it here for completeness.
I don't think it's adequate though, since it's not general purpose at all:
```rust
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let mut temp = None;
    let mut setpoint = None;
    mq::simple_loop(vec![OFFICE_THERM, OFFICE_SETPOINT], |topic, payload| {
        match topic.as_str() {
            OFFICE_THERM => temp = from_slice::<Therm>(&payload).ok().map(|x| x.temperature),
            OFFICE_SETPOINT => setpoint = from_slice::<Decimal>(&payload).ok(),
            other => {
                error!("oh god oh fucc what is topic: `{}`", other);
                return mq::Ruling::Die;
            }
        }
        if let (Some(temp), Some(setpoint)) = (temp, setpoint) {
            mq::Ruling::Post(vec![("test/cool".into(), format!("{}", temp > setpoint))])
        } else {
            mq::Ruling::Nothing
        }
    })
    .await
}
```
(don't mind the async, the point is that the closure is not async, which allows the persistent `&mut`s)

**Comment by TotalKrill** [comment]
Yeah, I don't agree that end users should wrap the channels themself. My suggestion was based on the assumption that the async code we had was the mqtt client. And the high level sync code was to be the wrapping of that code. A simple client if you will. 

Most users will silently use the library, that's kind of what you want, because then it has solved their problem. 

I agree that the way to handle subscription in my code has its drawback and can become unwieldy quickly. I will think some more on that, but I think that having a client object with 'subscribe', 'publish'  and 'retain' methods on would be nice for end users.

I get wanting to manage the channels myself, but that is not intuitive for new users. I don't want to send a subscribtion, I want to use the client to subscribe.

**Comment by tekjar** [comment]
I'll try to consolidate all the concerns here and put down my opinion

> how would I handle failing connections here? or know when a reconnect has happened, or stuff like that.

They will be part of notification channel (implementation isn't complete yet)

> Why not just have good old `publish`, `subscribe`, `unsubscribe`, `disconnect` APIs

The problem is that they come with baggage. All these APIs are an abstraction over a channel. They hide that there is a channel underneath. Given rust doesn't have optional arguments, there'll be API blowup. `publish`, `try_publish`, `timeout_publish` (repeat these subscribe, unsubscribe, disconnect). We have these methods which just looks like channel `Sender` methods because we are trying hard to cover that this is a `Sender` internally. Even if we do this, notifications are on a channel `Receiver` which is not hidden by a callback. 

The advantage with channel interface is that people are already very familiar with it and there is symmetry (both outgoing and incoming are over a channel)

> I cant really put a finger on it, but this feels weird,

Does it feel new or does it feel wrong?

> What do you think about something like this for an API? Its quite similar to rumqtt. But separates the connection part from the client part, making the client able to be send and sync, while hiding the internals from a user if wanted

Yeah they are fine. But the  API and symmetry issues remain. I think the problem here is with the word `Client`.  `Connection` would be a better term I guess

```rust
let connection = rumqtt::Connection::new(options);
let (tx, rx) = connection.channel(10);
connection.start()
```

Also what internals (and why) are we hiding? That communication with eventloop is over a channel?

> A channel per subscription notifications

That's an interesting idea. I see some cool advantages and some issues which requires a bit more code. We should probably discuss this in a separate issue. But a single notification channel should be the default IMO



> I do like methods like `.publish` and `.subscribe` like @TotalKrill suggests, but I feel like end users should just wrap the channel themselves. In fact it's `Publish::new()` and such that I don't like, because I always end up making my own client with methods, because I need to for instance set retain to true sometimes, so I have `publish` and `retain` methods

AFAIU, we are wrapping these (be it inside the library or outside) for 2 reasons

- We are too used to and anchored to having a `Client` and `publish`, `subscribe` methods on it. 
- People reading documentation will most probably expect this because they used similar API in other languages

We are trying to cover the channel interface because we are choosing "Familiarity over correctness" 
 (Don't mean to say that there is anything wrong with it)

**Comment by amrx101** [comment]
This is all I can think of.

- A mechanism to handle disconnects of the `Client` is used very often in many organisations IMHO.
- `.publish`, `.subscribe` etc on `Client` provides familiarity to people who migrate from other languages, I had used `Golang's` `mqtt library` which has `Publish`, `Subscribe`. Familiarity may help in adoption. But we can forgo this if causes bloated API.

+1 for using `Connection` rather than `Client` as `Client` kicks in a search of methods like `publish`, `subscribe` etc.

**Comment by qm3ster** [comment]
Is `connection.cancel_handle()` necessary because users might be unable to drop a sender because they tried to send and it blocked forever?

How is subscription on reconnection handled?

And since we are already spawning a loop, I feel "Familiarity over correctness" `Client` is the way to go for dead simple usage. A `Sender` and a `Receiver` are not actually all that similar, they are just conceptually linked. So a `Client`/`Sender`/`Publisher`/`Publicist` with methods that construct and enqueue a message in one call are very attractive. Whereas the notification receiver should be an iterator.

**Comment by tekjar** [comment]
Ok I yield. We'll go with the familiar `Client` model with 12 APIs ( publish, subscribe, unsubscribe & disconnect * 3)

**Comment by tekjar** [comment]
Actually this doesn't have to be 12 APIs. Timeouts can be configured to be a part of `Client` and just have 4 APIs. Cool. I'll implement this today

**Comment by MightyPork** [comment]
You can also use things like `Option<Duration>` for the timeouts. What would be the difference between `publish` and `try_publish`?

**Comment by tekjar** [comment]
@MightyPork `publish` would block indefinitely when the channel is full while `try_publish` will fail immediately

**Comment by qm3ster** [comment]
but `publish` would also be fallible, with a timeout error?

**Comment by qm3ster** [comment]
@MightyPork Ok but imagine
`ShamefulClient`, `TimeoutClient` and `TryClient` :D

**Comment by TotalKrill** [comment]
I don't mind fallible functions, I just wish there was a shorthand in rust for 'unwrap()' similar to 'fallible_fun()?' imagine 'fallible_run()!!'

**Comment by TotalKrill** [comment]
Yeah, I know, I just write a lot of testing code, which is a form of real code. So having !! would just be a nice feature :)

**Comment by TotalKrill** [comment]
To bring the discussion back on track, I am interested in how the classic implementation went?

I also wanted to add that I appreciate your hard work and for listening to our opinions in your project, just don't take what we say as facts. You are the mastermind of this piece of software :)

**Comment by tekjar** [comment]
@TotalKrill Didn't get time the other day due to broker work. Here is a working example with client APIs

https://github.com/tekjar/rumq/blob/sync/rumq-client/examples/syncpubsub.rs


> I also wanted to add that I appreciate your hard work and for listening to our opinions in your project, just don't take what we say as facts. You are the mastermind of this piece of software :)

Thanks!! :)

**Comment by TotalKrill** [comment]
Sorry for the late feedback, At first glance I really like the new client APIs. I will try to find some time to tinker around with it and see how it handles different edge cases and such things. But the feel is quite nice :)

**Comment by tekjar** [comment]
Ahh..Even I so want to finish this and make a release on crates (by renaming this crate back to rumqtt)..Hope I find some time this week

**Comment by rcastill** [comment]
Hi, again, thanks for your work. I wonder if this sync api is intended to replace the async one? will it be deprecated? or continue to be developed and available?

**Comment by tekjar** [comment]
@rcastill It won't replace. Both will coexist

**Comment by tekjar** [comment]
Reorganized this repo and pushed rumqttc 0.0.1 to crates with synchronous client. Feel free to open a new issue to discuss this further
